
export const xlayerRwas = {
    "code": 9200,
    "data": [
        {
            "id": 64,
            "stockId": 1,
            "chainId": 1952,
            "address": "0x521432324BE19e5D42931B61BF6648337A70FDfD",
            "symbol": "AAPLc",
            "name": "Apple",
            "icon": "https://test.cyberalpha.cc/images/tokens/AAPL.png",
            "feeRate": 0,
            "minLimitTradeAmount": 20,
            "maxLimitTradeAmount": 1000000,
            "minMarketTradeAmount": 20,
            "maxMarketTradeAmount": 100000,
            "decimals": 6,
            "precision": 2,
            "state": 0,
            "sessionMask": 0,
            "weight": 1,
            "stockStatistics": {
                "stockId": 1,
                "totalShare": 14687356000,
                "circShare": 14662282333,
                "netIncomeLtm": 122575,
                "netIncomeLastYear": 112010,
                "netAsset": 106491,
                "onChainAddr": null,
                "eps": 7.46,
                "epsTtm": 8.249052
            },
            "startTradingTime": 0,
            "endTradingTime": 0,
            "showState": true,
            "listingState": true,
            "createTime": 1759991771
        },
        {
            "id": 77,
            "stockId": 14,
            "chainId": 1952,
            "address": "0x3Ac2763d86B3581BAF7D6FaE130546C22cAa31da",
            "symbol": "SMCIc",
            "name": "Supermicro",
            "icon": "https://test.cyberalpha.cc/images/tokens/SMCI.png",
            "feeRate": 0,
            "minLimitTradeAmount": 20,
            "maxLimitTradeAmount": 1000000,
            "minMarketTradeAmount": 20,
            "maxMarketTradeAmount": 100000,
            "decimals": 6,
            "precision": 2,
            "state": 0,
            "sessionMask": 6,
            "weight": 36,
            "stockStatistics": {
                "stockId": 14,
                "totalShare": 646873027,
                "circShare": 547865170,
                "netIncomeLtm": 1247.39,
                "netIncomeLastYear": 1048.854,
                "netAsset": 7575.43,
                "onChainAddr": null,
                "eps": 1.678193,
                "epsTtm": 1.907496
            },
            "startTradingTime": 0,
            "endTradingTime": 0,
            "showState": true,
            "listingState": true,
            "createTime": 1759991771
        },
        {
            "id": 78,
            "stockId": 77,
            "chainId": 1952,
            "address": "0xD7CfbfEd27AfecFe8871b382Ca61ea639e177D27",
            "symbol": "NFLXc",
            "name": "Netflix",
            "icon": "https://test.cyberalpha.cc/images/tokens/NFLX.png",
            "feeRate": 0,
            "minLimitTradeAmount": 20,
            "maxLimitTradeAmount": 1000000,
            "minMarketTradeAmount": 20,
            "maxMarketTradeAmount": 100000,
            "decimals": 6,
            "precision": 2,
            "state": 0,
            "sessionMask": 6,
            "weight": 35,
            "stockStatistics": {
                "stockId": 15,
                "totalShare": 4210798528,
                "circShare": 4181397343,
                "netIncomeLtm": 13373.641,
                "netIncomeLastYear": 10981.201,
                "netAsset": 31126.399,
                "onChainAddr": null,
                "eps": 2.53,
                "epsTtm": 3.095907
            },
            "startTradingTime": 0,
            "endTradingTime": 0,
            "showState": true,
            "listingState": true,
            "createTime": 1759991771
        },
        {
            "id": 80,
            "stockId": 17,
            "chainId": 1952,
            "address": "0x39DFa5a6ec55D42E5BaCF93BcF70e94073A94474",
            "symbol": "MSTRc",
            "name": "MicroStrategy",
            "icon": "https://test.cyberalpha.cc/images/tokens/MSTR.png",
            "feeRate": 0,
            "minLimitTradeAmount": 20,
            "maxLimitTradeAmount": 1000000,
            "minMarketTradeAmount": 20,
            "maxMarketTradeAmount": 100000,
            "decimals": 6,
            "precision": 2,
            "state": 0,
            "sessionMask": 15,
            "weight": 33,
            "stockStatistics": {
                "stockId": 17,
                "totalShare": 351601750,
                "circShare": 330974783,
                "netIncomeLtm": -12173.452,
                "netIncomeLastYear": -3848.152,
                "netAsset": 36651.357,
                "onChainAddr": null,
                "eps": -15.232727,
                "epsTtm": -43.006188
            },
            "startTradingTime": 0,
            "endTradingTime": 0,
            "showState": true,
            "listingState": true,
            "createTime": 1759991771
        },
    ],
    "message": null
}

export const xplayerTokens = {
    "code": 9200,
    "data": [
        {
            "id": 1,
            "chainId": 1952,
            "address": "0x9A0F5D3aac1F9aE8f92CC9babf27aac82d933e95",
            "symbol": "USDTX",
            "name": "Tether USD",
            "icon": "https://test.cyberalpha.cc/images/tokens/usdt.png",
            "decimals": 18,
            "precision": 2,
            "state": 1
        }
    ],
    "message": null
}